### ISSUE TITLE
How to add aliases?

### ISSUE THREAD

**Issue by brahama** [bodgit/puppet-postfix#1]
Hi! checking out your module.

Does it support adding aliases directly from it? i mean like the campto module that you put in hiera the alias and it adds it automatically, with all the reload and newaliases run.

Cheers!

**Comment by bodgit** [comment]
I think the camptocamp module only handles running `newaliases`, it's using the standard `mailalias` Puppet resource type to manage the alias entries. Now, I think currently my module expects to manage the source file as a whole but I suppose it could be enhanced to allow something else to manage the source file and only trigger running `newaliases` or `postmap /etc/aliases` so it could be notified by `mailalias` or `concat` resource types.

**Comment by brahama** [comment]
Didn't check how camptocamp modules does it. Its handy cause as you mention, there is no need to manage the file separately in my profile for instance. and it takes care of notifying newaliases to update the db. Do you have any preference or planning for this?

Thanks and Cheers!

**Comment by bodgit** [comment]
FYI this has been finally implemented, you can do something like this:
```puppet
include ::postfix

::postfix::lookup::database { '/etc/aliases':
  type => 'hash',
}

Mailalias <||> -> ::Postfix::Lookup::Database['/etc/aliases']
```
And then create any `mailalias` resources as usual and the map will be automatically compiled
