### ISSUE TITLE
Update puppetlabs-stdlib dependancy for version 5

### ISSUE THREAD

**Issue by sazzle2611** [bodgit/puppet-postfix#11]
We currently use this module with puppetlabs-stdlib v5.2.0 and it works great but whenever we want to install new modules we get an error that not all dependencies can be satisfied so we have to then add the --ignore-dependencies flag and then have to install all dependencies manually.

If we downgrade to puppetlabs-stdlib < v5 then we will have the same problem as we have other modules that require version greater than 5.

The current situation is workable but it's a pain so would really appreciate it if this could be done.

This would also need to be applied to bodgit-bodgitlib and bodgit-sasl to fix our problem.

Thanks,
Sarah

**Comment by bodgit** [comment]
They're up to stdlib v6.5.0 currently so I should just make the upper requirement < 7, so long as nothing I've depended on has been removed completely. Easy enough to test though.

**Comment by bodgit** [comment]
I've actually restarted converting my modules to use PDK, I've just done bodgitlib as that's a very simple module and I'm going to convert sasl and postfix as a priority next. As part of that work I will update the various module requirements.

**Comment by sazzle2611** [comment]
That's great, thank you very much!!

**Comment by bodgit** [comment]
I've now published updated SASL and Postfix modules that allow newer versions of stdlib.
