### ISSUE TITLE
Always performs change... 

### ISSUE THREAD

**Issue by brahama** [bodgit/puppet-postfix#2]
It always does a change

Notice: /Stage[main]/Postfix::Config/Postfix_master[smtp/inet]/ensure: created
Debug: /Stage[main]/Postfix::Config/Postfix_master[smtp/inet]: The container Class[Postfix::Config] will propagate my refresh event
Notice: /Stage[main]/Postfix::Config/Postfix_master[smtp/unix]/ensure: created
Debug: /Stage[main]/Postfix::Config/Postfix_master[smtp/unix]: The container Class[Postfix::Config] will propagate my refresh event
Debug: Class[Postfix::Config]: The container Stage[main] will propagate my refresh event
Info: Class[Postfix::Config]: Scheduling refresh of Class[Postfix::Service]
Info: Class[Postfix::Service]: Scheduling refresh of Service[postfix]

Centos6
Puppet4

**Comment by bodgit** [comment]
Can you include the relevant parts of your manifest for how you're applying the module please?

**Comment by brahama** [comment]
Hi bodgit!

Sure, Thanks for the response.

Its inside a profile.
```
class profile::mail {
  class {'::postfix':
    myhostname          => $::fqdn,
    myorigin            => $::fqdn,
    append_dot_mydomain => 'yes',
    masquerade_domains  => [$::fqdn],
  }
}
```
And in hiera

postfix::relayhost: 'mail.domain.com'
postfix::always_bcc: 'brahama@domain.com'

Thanks!

**Comment by bodgit** [comment]
So, I've just spun up a CentOS 6 vagrant box (`puppetlabs/centos-6.6-64-nocm`), installed the Puppet 4 package and applied the following manifest:

```puppet
class {'::postfix':
  myhostname          => $::fqdn,
  myorigin            => $::fqdn,
  append_dot_mydomain => 'yes',
  masquerade_domains  => [$::fqdn],
  relayhost           => 'mail.domain.com',
}
```

First run:

```
[root@wxw-mfdb-01-d ~]# puppet apply -tv test.pp 
Info: Loading facts
Notice: Compiled catalog for wxw-mfdb-01-d.example.com in environment production in 1.11 seconds
Info: Applying configuration version '1469476847'
Notice: /Stage[main]/Postfix::Config/Postfix_main[append_dot_mydomain]/ensure: created
Notice: /Stage[main]/Postfix::Config/Postfix_main[debugger_command]/value: value changed 'PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
	 ddd $daemon_directory/$process_name $process_id & sleep 5' to 'PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin ddd $daemon_directory/$process_name $process_id & sleep 5'
Notice: /Stage[main]/Postfix::Config/Postfix_main[masquerade_domains]/ensure: created
Notice: /Stage[main]/Postfix::Config/Postfix_main[myhostname]/ensure: created
Notice: /Stage[main]/Postfix::Config/Postfix_main[myorigin]/ensure: created
Notice: /Stage[main]/Postfix::Config/Postfix_main[relayhost]/ensure: created
Notice: /Stage[main]/Postfix::Config/Postfix_master[relay/unix]/command: command changed 'smtp
	-o smtp_fallback_relay=' to 'smtp -o smtp_fallback_relay='
Info: Class[Postfix::Config]: Scheduling refresh of Class[Postfix::Service]
Info: Class[Postfix::Service]: Scheduling refresh of Service[postfix]
Notice: /Stage[main]/Postfix::Service/Service[postfix]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 2.79 seconds
```

Changes applied correctly. Second run:

```
[root@wxw-mfdb-01-d ~]# puppet apply -tv test.pp 
Info: Loading facts
Notice: Compiled catalog for wxw-mfdb-01-d.example.com in environment production in 1.13 seconds
Info: Applying configuration version '1469476859'
Notice: Applied catalog in 0.25 seconds
```

The second run changes nothing.

Can you include your `/etc/postfix/master.cf`? I suspect there's already some customisation there that might be confusing things.

**Comment by brahama** [comment]
Sure!

`
# file managed by puppet
#
# Postfix master process configuration file.  For details on the format
# of the file, see the master(5) manual page (command: "man 5 master").
#
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (yes)   (never) (100)
# ==========================================================================
#smtp      inet  n       -       n       -       -       smtpd
#submission inet n       -       n       -       -       smtpd
#  -o smtpd_enforce_tls=yes
#  -o smtpd_sasl_auth_enable=yes
#  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
#smtps     inet  n       -       n       -       -       smtpd
#  -o smtpd_tls_wrappermode=yes
#  -o smtpd_sasl_auth_enable=yes
#  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
#628      inet  n       -       n       -       -       qmqpd
pickup    fifo  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      fifo  n       -       n       300     1       qmgr
#qmgr     fifo  n       -       n       300     1       oqmgr
tlsmgr    unix  -       -       n       1000?   1       tlsmgr
rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
smtp      unix  -       -       n       -       -       smtp
# When relaying mail as backup MX, disable fallback_relay to avoid MX loops
relay     unix  -       -       n       -       -       smtp -o smtp_fallback_relay=
#       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       n       -       -       lmtp
anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache
#
# ====================================================================
# Interfaces to non-Postfix software. Be sure to examine the manual
# pages of the non-Postfix software to find out what options it wants.
#
# Many of the following services use the Postfix pipe(8) delivery
# agent.  See the pipe(8) man page for information about ${recipient}
# and other message envelope options.
# ====================================================================
#
# maildrop. See the Postfix MAILDROP_README file for details.
# Also specify in main.cf: maildrop_destination_recipient_limit=1
#
#
# The Cyrus deliver program has changed incompatibly, multiple times.
#
# Cyrus 2.1.5 (Amos Gouaux)
# Also specify in main.cf: cyrus_destination_recipient_limit=1
#
# See the Postfix UUCP_README file for configuration details.
#
#
# Other external delivery methods.   
#
proxywrite unix - - n - 1 proxymap   
retry unix - - n - - error

I will try to remove the package and run puppet there.
`

**Comment by brahama** [comment]
Hey bodgit, Just removed postfix and removed all postfix files; and run puppet so it is installed by the module and still same issue :S

**Comment by bodgit** [comment]
So your `master.cf` is different from the default as it has the `smtp/inet` service commented out. If I do that then I see the same issue:

```
# puppet apply -tv test.pp 
Info: Loading facts
Notice: Compiled catalog for localhost.localdomain in environment production in 1.16 seconds
Info: Applying configuration version '1469530406'
Notice: /Stage[main]/Postfix::Config/Postfix_master[smtp/inet]/ensure: created
Notice: /Stage[main]/Postfix::Config/Postfix_master[smtp/unix]/ensure: created
Info: Class[Postfix::Config]: Scheduling refresh of Class[Postfix::Service]
Info: Class[Postfix::Service]: Scheduling refresh of Service[postfix]
Notice: /Stage[main]/Postfix::Service/Service[postfix]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 0.94 seconds
```

What is odd is that `smtp/unix` is already defined so that shouldn't need to be created, there's something funny going on. I'll take a look.

**Comment by bodgit** [comment]
I've pushed v1.0.1 to the forge that contains the fix for this. Thanks for the bug report.

**Comment by brahama** [comment]
Cool bodgit! That was quick! Thanks.
I'll try it now and come back to you with the result

**Comment by brahama** [comment]
Great mate! All working. Thanks. You can close it!
