### ISSUE TITLE
Define master.cf entries in hiera?

### ISSUE THREAD

**Issue by doubletwist13** [bodgit/puppet-postfix#5]
Maybe I'm missing something [as are the folks in #puppet] but there doesn't seem to be a way to declare entries in hiera to be added to master.cf? 

This capability would be nice.

**Comment by bodgit** [comment]
So what you're basically after is a class parameter for passing in a bunch of `postfix::master` resources in hash form?

**Comment by bodgit** [comment]
> So what you're basically after is a class parameter for passing in a bunch of `postfix::master` resources in hash form?

There already is such a parameter, see the `default_services` parameter which contains the list of services to manage by default. Copying and extending that set in Hiera should allow you to do that.
